name: Java CI with Maven

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build
        run: mvn -B package

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-build
          path: target/*.jar


  unit_test:
    runs-on: self-hosted
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: Run tests
        run: mvn test


  security_scan:
    runs-on: self-hosted
    needs: unit_test

    steps:
      - uses: actions/checkout@v4

      - name: Run Trivy scan
        run: trivy fs --format json -o trivy-report.json .

      - name: Run Gitleaks scan
        run: gitleaks detect --source . --report-path gitleaks-report.json --report-format json

      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: |
            trivy-report.json
            gitleaks-report.json


    
